name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and Export static site
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [ "$REPO_NAME" = "$OWNER.github.io" ]; then
            export NEXT_PUBLIC_BASE_PATH=""
          else
            export NEXT_PUBLIC_BASE_PATH="/$REPO_NAME"
          fi
          echo "Using NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH"
          npm run build
          npm run export

      - name: Prepare GitHub Pages artifacts
        run: |
          touch out/.nojekyll
          # 复制 index.html 作为 404.html 以支持 SPA 路由
          cp out/index.html out/404.html || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
